name: quizapp
description: Flutter Quiz Application.
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  share_plus: 4.4.0
  fl_chart: ^0.55.2
  pie_chart: ^5.3.2
  flutter_rating_bar: ^4.0.1
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
